object Libs {
    const val coreKtx = "androidx.core:core-ktx:${Versions.coreKtx_version}"
    const val appcompat = "androidx.appcompat:appcompat:${Versions.appcompat_version}"
    const val material = "com.google.android.material:material:${Versions.material_version}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout_version}"
    const val koinScope = "io.insert-koin:koin-androidx-scope:${Versions.koin_version}"
    const val koinViewModel = "io.insert-koin:koin-androidx-viewmodel:${Versions.koin_version}"
    const val lifecycleViewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle_version}"
    const val lifecycleRuntime = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycle_version}"
    const val fragment = "androidx.fragment:fragment:${Versions.fragment_version}"
    const val fragmentKtx = "androidx.fragment:fragment-ktx:${Versions.fragment_version}"
    const val gson = "com.google.code.gson:gson:${Versions.gson_version}"
    const val okhttp = "com.squareup.okhttp3:okhttp:${Versions.okhttp_version}"
    const val okhttpLoggingInterceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttp_version}"
    const val apolloRuntime = "com.apollographql.apollo3:apollo-runtime:${Versions.apollo_version}"
    const val apolloApi = "com.apollographql.apollo3:apollo-api:${Versions.apollo_version}"
    const val apolloCache = "com.apollographql.apollo3:apollo-normalized-cache-sqlite:${Versions.apollo_version}"
    const val coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutines_version}"
    const val coroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutines_version}"
    const val pagingRuntime = "androidx.paging:paging-runtime:${Versions.pagingRuntime_version}"
    const val annotation = "androidx.annotation:annotation:${Versions.annotation_version}"
}
