object TestLibs {
    const val junitTest = "junit:junit:${Versions.junit_version}"
    const val extJunitTest = "androidx.test.ext:junit:${Versions.androidxJunit_version}"
    const val espressoTest = "androidx.test.espresso:espresso-core:${Versions.espresso_version}"
    const val koinTest = "io.insert-koin:koin-test:${Versions.koin_version}"
    const val koinCoreTest = "io.insert-koin:koin-test-core:${Versions.koin_version}"
    const val apolloTestingSupport = "com.apollographql.apollo3:apollo-testing-support:${Versions.apollo_version}"
    const val apolloMockserver = "com.apollographql.apollo3:apollo-mockserver:${Versions.apollo_version}"
    const val mockkUnitTest = "io.mockk:mockk:${Versions.mockk_version}"
    const val mockkAndroidTest = "io.mockk:mockk-android:${Versions.mockk_version}"
    const val coroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test-jvm:${Versions.coroutines_version}"
    const val turbineTest = "app.cash.turbine:turbine:${Versions.turbine_version}"
    const val runnerTest = "androidx.test:runner:${Versions.testRules_version}"
    const val kotlinTest = "org.jetbrains.kotlin:kotlin-test:${Versions.kotlin_version}"
    const val kotlinJUnitTest = "org.jetbrains.kotlin:kotlin-test-junit:${Versions.kotlin_version}"
}
